baseURL = "https://jenever-tech.gitlab.io/jenever-tech/"
languageCode = "zh-tw"
title = "晴玖科技JeneverTech"
theme = "syna"
enableGitInfo = false
version = "0.1.0"
publishdir = "public"

# Google Analytics tracking
googleAnalytics = "UA-46261454-2"

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[params]
  name = "JeneverTech"
  description = ""

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
  #  favicon_ico_sizes = "16x16 32x32"
  #  favicon_png = "favicon.png"
  #  favicon_svg = "favicon.svg"

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#00838F"
    secondary = "#868e96"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "#services"
  name = "Services"
  weight = 20

[[menu.main]]
  url = "/about"
  name = "About Us"
  weight = 30

[[menu.footer]]
  url = "mailto:maslow21@jenever-tech.com"
  name = "Email: maslow21@jenever-tech.com"
  weight = 10

[[menu.footer]]
  name = "10 am. ~ 19 pm. (Mon. ~ Tru.)"
  weight = 30

[[menu.footer]]
  name = "10 am. ~ 18 pm. Fri."
  weight = 30

